In [67]:
import numpy as np


In [68]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [69]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[2,:]

array([35, 40, 45])

In [84]:
arr_2d[1:2,0:3]

array([[20, 25, 30]])

In [87]:
arr= np.arange(1,11)

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
bool_arr = arr>5

In [94]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [95]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [96]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [100]:
arr1 = ([1,2,3,4,5,6,7,8,9])

In [101]:
arr1[arr%2==0]

TypeError: only integer scalar arrays can be converted to a scalar index

In [103]:
arr_2d = np.arange(50).reshape(5,10)

In [104]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [110]:
arr_2d[2,3:5]

array([23, 24])

In [111]:
arr = np.arange(11)

In [112]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [113]:
arr1 = np.arange(12)

In [119]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [120]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [121]:
np.max(arr)

10

In [122]:
arr.max()

10

In [123]:
arr.min()

0